version: "3.7"
services:
  nginx:
    image: nginx:1.19.6
    ports:
      - "443:443"
    volumes:
      - ./data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/cert:/etc/nginx/cert
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env.local
