export enum Errors {
  REQUIRED_FIELDS_MISSING,
  INVALID_EMAIL,
  PASSWORD_REQUIREMENT,
  TOS_NOT_ACCEPTED,
  INVALID_PASSWORD,
  WRONG_SIGN_IN_METHOD,
  INVALID_PASSWORD_RESET_TOKEN,
  FORM_NOT_FOUND,
  FORM_NOT_OPEN,
  TICKET_INVALID,
  TICKET_SOLD_OUT,
  ORDER_NOT_FOUND,
  ORDER_NOT_PENDING,
}

export enum FormErrors {
  TITLE_MISSING,
  TICKET_MISSING,
  TICKET_MISSING_DESCRIPTION,
  TICKET_DUPLICATE_DESCRIPTION,
  TICKET_TOO_LOW_PRICE,
}
